export const translations = {
  en: {
    appName: "WellDash",
    navDashboard: "Dashboard",
    navAdmin: "Admin Panel",
    navParent: "Parent Portal",
    navCanteen: "Canteen Menu",
    createdBy: "Created by Fadila, Duaa, and Rania",
    dashboardTitle: "School Wellness Dashboard",
    healthyChoices: "Healthy Choices (Logged Class)",
    activityTracker: "Daily Class Activity Tracker",
    attendedActivity: "Attended Activity Class",
    intensity: "Intensity",
    activeBreak: "Had Active Break",
    teacher: "Teacher",
    leaderboardTitle: "Abu Dhabi Schools Leaderboard",
    challengesTitle: "Weekly Challenges",
    menuTitle: "Canteen Digital Menu",
    smartChoice: "Smart Choice +10 Points for Your Class",
    print: "Print Report",
    share: "Share with Ministry of Health",
    sharedMessage: "Achievements have been shared successfully!",
    adminTitle: "Admin Data Entry",
    grade: "Grade",
    selectGrade: "Select Grade",
    numberOfStudents: "Number of Students Attended",
    enterNumberOfStudents: "Enter number of students",
    logClassActivity: "Log Class Activity",
    yes: "Yes",
    no: "No",
    low: "Low",
    medium: "Medium",
    high: "High",
    selectIntensity: "Select Intensity",
    teacherName: "Teacher's Name",
    enterTeacherName: "Enter Teacher's Name",
    submit: "Submit Data",
    parentTitle: "Parent Portal",
    healthPromotion: "Family Health Promotion",
    healthTip1: "Encourage at least 60 minutes of physical activity daily.",
    healthTip2: "Make half your family's plate fruits and vegetables.",
    healthTip3: "Choose water over sugary drinks.",
    challengeInsights: "Weekly Challenge Insights",
    challengeInsightText: "This week's 'Healthy Swap' challenge is a great opportunity to discuss healthy snack alternatives with your child!",
    healthAdvisor: "AI Health Advisor",
    askHealthQuestion: "Ask a question about family health...",
    getAdvice: "Get Advice",
    canteenTitle: "Canteen Digital Menu",
    smoothieMakerTitle: "Create Your Own Smoothie",
    selectIngredients: "Select your ingredients:",
    yourSmoothie: "Your Smoothie",
    makeSmoothie: "Make Smoothie!",
    smoothieMade: "Your healthy smoothie is ready! +25 points!",
  },
  ar: {
    appName: "ويل داش",
    navDashboard: "لوحة التحكم",
    navAdmin: "لوحة الإدارة",
    navParent: "بوابة أولياء الأمور",
    navCanteen: "قائمة المقصف",
    createdBy: "تم إنشاؤه بواسطة فضيلة، دعاء، ورانيا",
    dashboardTitle: "لوحة تحكم الصحة المدرسية",
    healthyChoices: "الاختيارات الصحية (للصف المسجل)",
    activityTracker: "متتبع النشاط اليومي للصف",
    attendedActivity: "حضر حصة النشاط",
    intensity: "الشدة",
    activeBreak: "أخذ استراحة نشطة",
    teacher: "المعلم",
    leaderboardTitle: "لوحة صدارة مدارس أبوظبي",
    challengesTitle: "التحديات الأسبوعية",
    menuTitle: "قائمة المقصف الرقمية",
    smartChoice: "اختيار ذكي +10 نقاط لصفك",
    print: "طباعة التقرير",
    share: "مشاركة مع وزارة الصحة",
    sharedMessage: "تمت مشاركة الإنجازات بنجاح!",
    adminTitle: "إدخال بيانات المسؤول",
    grade: "الصف الدراسي",
    selectGrade: "اختر الصف",
    numberOfStudents: "عدد الطلاب الحاضرين",
    enterNumberOfStudents: "أدخل عدد الطلاب",
    logClassActivity: "تسجيل نشاط الصف",
    yes: "نعم",
    no: "لا",
    low: "منخفضة",
    medium: "متوسطة",
    high: "عالية",
    selectIntensity: "اختر الشدة",
    teacherName: "اسم المعلم",
    enterTeacherName: "أدخل اسم المعلم",
    submit: "إرسال البيانات",
    parentTitle: "بوابة أولياء الأمور",
    healthPromotion: "تعزيز صحة الأسرة",
    healthTip1: "شجع على ممارسة 60 دقيقة على الأقل من النشاط البدني يوميًا.",
    healthTip2: "اجعل نصف طبق عائلتك من الفواكه والخضروات.",
    healthTip3: "اختر الماء بدلاً من المشروبات السكرية.",
    challengeInsights: "رؤى حول تحدي الأسبوع",
    challengeInsightText: "تحدي 'التبديل الصحي' لهذا الأسبوع فرصة رائعة لمناقشة بدائل الوجبات الخفيفة الصحية مع طفلك!",
    healthAdvisor: "مستشار الصحة الذكي",
    askHealthQuestion: "اسأل سؤالاً عن صحة الأسرة...",
    getAdvice: "احصل على نصيحة",
    canteenTitle: "قائمة المقصف الرقمية",
    smoothieMakerTitle: "اصنع عصيرك الخاص",
    selectIngredients: "اختر مكوناتك:",
    yourSmoothie: "عصيرك",
    makeSmoothie: "اصنع العصير!",
    smoothieMade: "عصيرك الصحي جاهز! +25 نقطة!",
  }
};
